def throw_interrupt_error():
    raise RuntimeError("Thread Interrupted")
